### ISSUE TITLE
Cannot install via pipenv

### ISSUE THREAD

**Issue by rossm6** [dimagi/django-cte#37]
(fb_marketplace) ross@ross-Aspire-TC-780:~/Desktop/web_dev/projects/fb_marketplace$ pipenv install django-cte
Installing django-cte…
Adding django-cte to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (00d562) out of date, updating to (60deb0)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
Traceback (most recent call last):
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 758, in resolve_packages
    results = clean_results(results, resolver, project)
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 640, in clean_results
    entry_dict = translate_markers(entry.get_cleaned_dict(keep_outdated=False))
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 239, in get_cleaned_dict
    self.validate_constraints()
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 565, in validate_constraints
    constraints = self.get_constraints()
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 493, in get_constraints
    pipfile_constraint = self.get_pipfile_constraint()
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 507, in get_pipfile_constraint
    return self.constraint_from_parent_conflicts()
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 527, in constraint_from_parent_conflicts
    if not p.requirements:
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 625, in __getattribute__
    return super(Entry, self).__getattribute__(key)
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 370, in requirements
    self.project.environment.get_package_requirements(self.name)
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/environment.py", line 708, in get_package_requirements
    return [self._get_requirements_for_package(p, key_tree) for p in nodes]
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/environment.py", line 708, in <listcomp>
    return [self._get_requirements_for_package(p, key_tree) for p in nodes]
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/environment.py", line 685, in _get_requirements_for_package
    d['dependencies'] = [
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/environment.py", line 686, in <listcomp>
    cls._get_requirements_for_package(c, key_tree, parent=node,
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/environment.py", line 677, in _get_requirements_for_package
    d = node.as_dict()
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/vendor/pipdeptree.py", line 284, in as_dict
    'installed_version': self.installed_version,
  File "/home/ross/.local/lib/python3.8/site-packages/pipenv/vendor/pipdeptree.py", line 168, in __getattr__
    return getattr(self._obj, key)
AttributeError: 'Requirement' object has no attribute 'installed_version'

**Comment by rossm6** [comment]
Solved by upgrading my pip and pipenv.
